### ISSUE TITLE
Work work work

### ISSUE THREAD

**Issue by steeeved** [StephenMaina2019/Max-Project#1]
Are we still doing this or what?

**Comment by Trex-web** [comment]
Yeah i have been looking inton other systems alike and we are far from over

**Comment by steeeved** [comment]
What should we be doing about it?

**Comment by Trex-web** [comment]
Can we insert a picture in the system that will appear as the background
instead of the colours?

**Comment by steeeved** [comment]
Ok, send me the picture

**Comment by Trex-web** [comment]
Hio itakua kwa log in as back ground

**Comment by steeeved** [comment]
Where is the picture?

**Comment by Trex-web** [comment]
Hii nayo itakua onr ume log in

**Comment by Trex-web** [comment]
Umezi get???

**Comment by steeeved** [comment]
Zii

**Comment by Trex-web** [comment]
I believe i asked you a question...

**Comment by steeeved** [comment]
I believe I answered it

**Comment by steeeved** [comment]
I have added the image as the background. It looks good but the frames are making it unclear because of their solid color. Please download the files and see

**Comment by Trex-web** [comment]
I've run the code but i am receiveing an error-No module named 'PIL'

**Comment by steeeved** [comment]
Run 'pip install pillow' on cmd

**Comment by Trex-web** [comment]
Inaniambia invalid syntax

**Comment by Trex-web** [comment]
![IMG_20210716_094402.jpg](https://user-images.githubusercontent.com/79729277/125904096-ec611de8-e5c7-4a50-aed4-39edd318371d.jpg)
Tunaeza kua na log in page kaa hii

**Comment by steeeved** [comment]
Eee

**Comment by Trex-web** [comment]
Wazii cheza kaa wewe alfu images utoe

**Comment by steeeved** [comment]
Stuff yetu ni Rent Management System. Sii hospital

**Comment by Trex-web** [comment]
Yeah sini majina tuu utachange

**Comment by steeeved** [comment]
Niweke nini
